[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
miette = { version = "7.5.0", features = ["fancy"] }
rand = "0.9.0"
text_io = "0.1.12"
thiserror = "2.0.12"
